export const COLLECTIONS = {
  ABOUTUS: "aboutUs",
  NEWS: "news",
  ADMIN: "admin",
  INSTITUTION: "institution",
  TRAVEL: "travel",
  EVENT: "event",
  LEGALITY: "legality",
  KEEPSAKE: "keepsake",
  EMPLOYEE: "employee",
  OFFERS: "offers",
  REPORT: "report",
  VIDEO: "video",
  RESOURCES: "resources",
  SCENIC: "snenicspot",
};
