import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./components/header";
import { MainMenu } from "./components/mainMenu";
import { InfoAimag } from "./components/infoAimag";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <MainMenu />
        <InfoAimag />
        {children}
      </body>
    </html>
  );
}
